# Generated by Django 2.2 on 2020-08-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='profile_image',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
