# Generated by Django 2.2 on 2020-08-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contestant_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='profile_image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
